# Setup
title: Yayun's Blog
tagline:
baseurl: ""
paginate: 1

# About/contact
author:
  name: yayunx 
  url: http://yayun.github.io
  avatar_url: https://avatars2.githubusercontent.com/u/2765064?s=60&v=4

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
# highlighter: pygments
kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'id-'
