# Setup
title: Yayun's Blog
tagline:
baseurl: ""
paginate: 1

# About/contact
author:
  name: Yayun
  url: http://yayun.github.io
  avatar_url: http://tva4.sinaimg.cn/crop.75.27.225.225.180/6978184djw1e9bshab384j20ag07t74w.jpg

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  auto_ids: true
  auto_id_prefix: 'id-'
